import Head from 'next/head'
import { Container, ModuleBorderWrap, Wrapper, Icon } from '../components/sharedstyles'
import Button from '../components/button';
import styled from 'styled-components';
import { CiSearch } from 'react-icons/ci';


export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ModuleBorderWrap>
        <Wrapper>
          <div>
            <Button text='Any token' />
            <Button text='Any chain' />
            <Button text='Any amount' />
          </div>
          <Icon>
            <CiSearch size={'20'} />
          </Icon>
        </Wrapper>
      </ModuleBorderWrap>

    </Container>
  )
}
